spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wemanage
    username: root
    password: admin123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        globally_quoted_identifiers: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
  sql:
    init:
      mode: never

